# Name.
title: The Forsaken

# Description.
description: The pilgrims walk the long road together.

# Content.
content: The Forsaken is a Post-Apocalyptic Roleplaying game.

# Links.
social:
  - platform: Download Forsaken
    url: google.com
  - platform: Twitter
    url: https://twitter.com/forsakengamedev
  - platform: Email
    url: forsakengame@protonmail.com
  - platform: Github
    url: https://github.com/forsakengame

# General settings.
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout.
half_side: right

# Full layout.
full_text_position: center # left, right or center