# Name.
title: The Forsaken

# Description.
description: The pilgrims walk the long road together.

# Content.
content: The Forsaken is a Post-Apocalyptic Roleplaying game.

# Links.
social:
  - platform: github
    url: https://github.com/brianmaierjr
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/brianmaierjr
  - platform: linkedin
    url: brianmaierjr

# General settings.
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout.
half_side: right

# Full layout.
full_text_position: center # left, right or center