# Name.
title: The Forsaken

# Description.
description: The Forsaken is a free Post-Apocalyptic Roleplaying game.

# Content.
content: The Forsaken is a free Post-Apocalyptic Roleplaying game.

# Links.
download:
  - platform: Windows Download
    url: https://google.com
  - platform: Mac Download
    url: https://google.com
  - platform: Linux Download
    url: https://google.com
    
social:
  - platform: Twitter
    url: https://twitter.com/forsakengamedev
  - platform: Github
    url: https://github.com/forsakengame
  - platform: Email
    url: email:forsakengame@protonmail.com

# General settings.
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout.
half_side: left

# Full layout.
full_text_position: right